# Multiple Linear Regression

## Importing the libraries

In [ ]:
import numpy as np;
import pandas as pd;
import matplotlib.pyplot as plot;

## Importing the dataset

In [ ]:
data=pd.read_csv('/content/drive/My Drive/ML:a-z/multiple linear regression/50_Startups.csv')
x=data.iloc[:,:-1].values
y=data.iloc[:,-1].values

In [23]:
print(x)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

In [ ]:
print(y)

## Encoding categorical data

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
x=np.asarray(ct.fit_transform(x))

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=0)

## Training the Multiple Linear Regression model on the Training set

In [ ]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Predicting the Test set results

In [ ]:
y_pred=regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

##Predicting results of new **data**

In [28]:
print(regressor.predict([[1,0,0,990000,830000,660000]]))

[859743.52]


##Printing the linear regression equation

In [31]:
coeff=regressor.coef_
inter=regressor.intercept_
print('y='+str(inter)+'+'+str(coeff[0])+'*Dummy var1+'+str(coeff[1])+'*Dummy var2+'+str(coeff[2])+'*Dummy var3+'+str(coeff[3])+'*R&D Spend+'+str(coeff[4])+'*Administration+'+str(coeff[5])+'*Marketing Spend')

y=42467.52924853204+86.63836917588786*Dummy var1+-872.64579087744*Dummy var2+786.0074217043534*Dummy var3+0.7734671927327668*R&D Spend+0.0328845975362384*Administration+0.03661002586397899*Marketing Spend
